function plotLameDim(link,lame_length,lame_width,lame_height)
%PLOTLAMEDIM Summary of this function goes here
%   Detailed explanation goes here
lame_height = lame_height/10;
X = [0 lame_width lame_width 0;...
    0 lame_width lame_width 0;...
    0 0 0 0;...
    lame_width lame_width lame_width lame_width;...
    0 lame_width lame_width 0;...
    0 lame_width lame_width 0];

Y = [0 0 0 0;...
    lame_length lame_length lame_length lame_length;...
    0 lame_length lame_length 0;...
    0 lame_length lame_length 0;...
    0 0 lame_length lame_length;...
    0 0 lame_length lame_length];

Z = [0 0 lame_height lame_height;...
        0 0 lame_height lame_height;...
        0 0 lame_height lame_height;...
        0 0 lame_height lame_height;...
        0 0 0 0
        lame_height lame_height lame_height lame_height];

C = [0.3,0.5,0.8];

surf(link,X,Y,Z,'FaceColor',C);
end

