function plotCapt(link,length,height,width,spacing)
%PLOTCAPT Fonction permettant d'afficher le capteur choisi sur le montage
%   On utilise cette fonction pour ajouter le capteur sur le montage du
%   prototype (en simulation) tout en gardant l'abstraction venant de la
%   sélection du capteur.

X = [0 width width 0;...
    0 width width 0;...
    0 0 0 0;...
    width width width width;...
    0 width width 0;...
    0 width width 0];

Y = [0 0 0 0;...
    length length length length;...
    0 length length 0;...
    0 length length 0;...
    0 0 length length;...
    0 0 length length];

Z_bot = [0 0 height height;...
        0 0 height height;...
        0 0 height height;...
        0 0 height height;...
        0 0 0 0
        height height height height];
    
Z_top = Z_bot + spacing;

C = [0.7,0.2,0.05];
fill3(link,X,Y,Z_bot,C,X,Y,Z_top,C);
end

