path = ".\default\default.mat";
dimensionStruct = struct('length',0.247, ...
                          'width',0.0733, ...
                          'height',0.10, ...
                          'pos_act',0.08, ...
                          'height_limits',[0,0.15], ...
                          'pos_limits',[0.015,0.10]);
                      
lameflexStruct = struct('length',0.247, ...
                        'width',0.0733, ...
                        'thick',0.00182, ...
                        'mass',0.0695, ...
                        'E',22.75e9, ...
                        'J',987.8e-8, ...
                        'wn',72, ...
                        'Att',0.3855464344, ...
						'mu',230);
                    
captStruct = struct('spacing',0.00457, ...
                    'Kp',0.008, ...
                    'Ki',0.06, ...
                    'Kd',0.00003, ...
                    'e0',0.002305, ...
                    'Vim',5, ...
                    'Vth',2);

timeStruct = struct('num_samples',0, ...
                    'duration',0);

actionStruct = struct('radius',0.015, ...
                      'L',0.001075, ...
                      'N',66, ...
                      'l',0.03, ...
                      'm', 0.100,...
                      'height',0.10);

allParamNames = {'Aucun', ...
             'Position du plateau', ...
             'Longueur de la lame', ...
             'Largeur de la lame', ...
             'Épaisseur de la lame', ...
             'Masse de la lame', ...
             'Constante b de la lame', ...
             'Module de Young E', ...
             'Moment daire J', ...
             'Atténuation de la lame', ...
             'Fréquence naturelle de la lame', ...
             'Densité de masse de la lame', ...
             'Rayon de la bobine', ...
             'Hauteur de la bobine' ...
             'Diamètre des spires', ...
             'Inductance L de lactionneur', ...
             'Nombre de spires', ...
             'Perméabilité relative de la bobine', ...
             'Constante Kp du PID', ...
             'Constante Ki du PID', ...
             'Constante Kd du PID', ...
             'Tension Vim du capteur de position', ...
             'Tension Vth du capteur de position'};

save(path,'dimensionStruct','lameflexStruct',...
    'captStruct','timeStruct','actionStruct',...
    'allParamNames');

clear 'dimensionStruct' 'lameflexStruct' ...
    'captStruct' 'timeStruct' 'actionStruct' ...
    'allParamNames' 'path'