path = ".\default\default.mat";
dimensionStruct = struct('length',50, ...
                          'width',9, ...
                          'height',15, ...
                          'pos_act',15, ...
                          'height_limits',[0,20], ...
                          'pos_limits',[0.15*15,100/4]);
                      
lameflexStruct = struct('length',50, ...
                        'width',9, ...
                        'thick',1.8, ...
                        'mass',10, ...
                        'E',0, ...
                        'J',0, ...
                        'wn',0, ...
                        'Att',0);
                    
captStruct = struct('spacing',4, ...
                    'Kp',0, ...
                    'Ki',0, ...
                    'Kd',0);
                
timeStruct = struct('num_samples',0, ...
                    'duration',0);
                
actionStruct = struct('radius',3, ...
                      'L',0, ...
                      'N',60, ...
                      'height',0.9*15);
                  
allParamNames = {'Aucun', ...
             'Position du plateau', ...
             'Longueur de la lame', ...
             'Largeur de la lame', ...
             'Épaisseur de la lame', ...
             'Masse de la lame', ...
             'Constante b de la lame', ...
             'Module de Young E', ...
             'Moment daire J', ...
             'Atténuation de la lame', ...
             'Fréquence naturelle de la lame', ...
             'Densité de masse de la lame', ...
             'Rayon de la bobine', ...
             'Hauteur de la bobine' ...
             'Diamètre des spires', ...
             'Inductance L de lactionneur', ...
             'Nombre de spires', ...
             'Perméabilité relative de ', ...
             'Constante Kp du PID', ...
             'Constante Ki du PID', ...
             'Constante Kd du PID', ...
             'Constante de temps du PID'};

save(path,'dimensionStruct','lameflexStruct',...
    'captStruct','timeStruct','actionStruct',...
    'allParamNames');

clear 'dimensionStruct' 'lameflexStruct' ...
    'captStruct' 'timeStruct' 'actionStruct' ...
    'allParamNames' 'path'